{% set version = "0.2.0" %}

package:
  name: supermercado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/supermercado/supermercado-{{ version }}.tar.gz
  sha256: 639372b946c31d63196a8fc38dde7eafa4c28ba9472a7a754996eb43b9e8a69b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - supermercado = supermercado.scripts.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - affine
    - click
    - click-plugins
    - cligj
    - mercantile
    - numpy
    - rasterio

test:
  imports:
    - supermercado
    - supermercado.scripts
  commands:
    - supermercado --help

about:
  home: https://github.com/mapbox/supermercado
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Supercharged mercantile

extra:
  recipe-maintainers:
    - ocefpaf
