travis:
  secure:
    BINSTAR_TOKEN: L/YeLFhTrrnbFb1XyU7RC8s3VNvRWbu6F1Rx02Z0Dm3xeL/DRYSIz8GbUdImNQv+F+RQdqtNxCTDl/7tk7RZSY8REEjNuj2WoU96DKhvQxw70UUaTL5aIxey1uBEEJ3IcP/VVzl8BcuGZyTt8B4pKbJ2KCdKROEKm+OukUzf9OnitQk9iaTfLq33ki/X3GO6+NQ1r5CbURceFf3LO0MhoSSXtIkeqoNogDKswVO/PqcHHLXnrBK1QdEHJForU+bs76oYkZpkTim7byGBQ9Yft1CwDU4AJlpLOKci8xqSosOt70UcNQ2hKAdcDYGuyy3QXU5r6FgzYUNle2+pn3nBVLoCTde6K5MYi2WeR+htMoL0Qh/El7OUHHDIs7Kk7/IwpWUnx43YneoaS/Iy+aa/mgficas5lL8SY0WNtGZG/RWqKKEfu09L0P8ldq2EFDPwHIsNopSWHIx5o17oXJheWremHj3vOBOGSq2Zguvtkkx2HiE5bxLS/ChIsQhTvENqlEcfR1+Ww6xuP9OPamlIUeOdMKARV+uPjeAmydtbKluT4jOsL415+64hxOPSvSYZmz5dSymzhq8eBeFhjUtdgF1z1PUwtP6y9/yNoBSijhcdTtD7MUlZ3zyll7AxkyqrV2RDm7HCgdz8/YRdh4U/r8Rzin/OvPtLyMQtOjAG9w0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
